name: countrify_light_example
description: Example app for the Countrify Light package
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.0.0
  flutter: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  countrify_light:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
